language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd basic-wallet
  - yarn install
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: basic-wallet/build
  on:
    branch: develop
