language: node_js
node_js:
  - "8.12.0"
dist: trusty

cache:
  directories:
  - basic-wallet/node_modules
  - burner-ui/node_modules
  - plugins/node_modules
  - exchange/node_modules

install:
  - cd basic-wallet
  - ./install-all.sh

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: basic-wallet/build
  on:
    branch: develop
